# Generated by Django 3.1.4 on 2021-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('FullPhone', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
