# Generated by Django 3.1.4 on 2021-01-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesolutionapp', '0002_user_tb_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('FullPhone', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user_tb',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
