# Generated by Django 3.1.4 on 2021-01-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesolutionapp', '0003_auto_20210106_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_tb',
            old_name='FullPhone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='worker_tb',
            old_name='FullPhone',
            new_name='phone',
        ),
    ]
