# Generated by Django 3.1.4 on 2021-01-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homesolutionapp', '0004_auto_20210106_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=30)),
                ('complaint', models.CharField(default='', max_length=30)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesolutionapp.user_tb')),
                ('workerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesolutionapp.worker_tb')),
            ],
        ),
    ]
