# Generated by Django 3.1.4 on 2021-01-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesolutionapp', '0006_admin_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='img')),
            ],
        ),
    ]
