# Generated by Django 3.1.4 on 2021-01-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesolutionapp', '0007_gallery_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_tb',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_tb',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='worker_tb',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
